### ISSUE TITLE
Every OTF font export is corrupt

### ISSUE THREAD

**Issue by dylanh724** [glyphr-studio/Glyphr-Studio-Desktop#10] opened 2016-09-08 08:51 UTC
Not quite sure what else to add -- all attempts have resulted in corruption. Windows 10. Tried the desktop version after the web version would crash progressively and consecutively. Anyone else getting this?

EDIT: SVG too.

**Comment by Autre31415** [comment] 2016-09-10 01:07
I was able to reproduce this on both Mac OS and Windows. Turns out the export buttons rely on some browser quirks that don't translate so well in Electron. A fix is in the works.

**Closed** 2016-09-10 17:23 UTC
Labels: bug

**Comment by Autre31415** [comment] 2016-09-10 17:52
Fixed in latest release https://github.com/glyphr-studio/Glyphr-Studio-Desktop/releases/tag/v0.2.0-beta
